scraping_project/scraping_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
     path(r'web_interface/', include('web_interface.urls')),
]

scraping_project/web_interface/urls.py
from django.urls import path

from . import views

app_name = 'web_interface'
urlpatterns = [
    path('',views.viewdata,name='viewdata'),
    path('search/',views.searchdata,name='searchdata'),

]

scraping_project/web_interface/models.py
from django.db import models
from jsonfield import JSONField
# Create your models here.

class ScrapyItem(models.Model):
    unique_id = models.CharField(max_length=100, null=True)
    snapdeal_data = JSONField() # this stands for our crawled data
    paytm_data = JSONField() # this stands for our crawled data

scraping_project/web_interface/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,Http404,JsonResponse
from django.template import loader
from django.utils import timezone
from django.http import HttpResponse,HttpResponseRedirect,Http404,JsonResponse
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from uuid import uuid4
from urllib.parse import urlparse
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.views.decorators.http import require_POST, require_http_methods
from django.views.decorators.csrf import csrf_exempt
from scrapyd_api import ScrapydAPI
from scrapy import signals
from scrapy.crawler import Crawler, CrawlerProcess,CrawlerRunner
from web_scraper.web_scraper.spiders.paytm_crawler import PaytmCrawlerSpider
from twisted.internet import reactor
from web_interface.models import ScrapyItem
import scrapy,time
# Create your views here.

scrapyd = ScrapydAPI('http://localhost:6800')

def searchdata(request):
    if 'q' in request.GET:
        querystring = request.GET.get('q').strip()
        if len(querystring) == 0:
            return redirect('/search/')

        results= []
        url = request.GET.get('q', None)
        #page = request.GET.get('page')
        unique_id = str(uuid4())
        settings = {
            'unique_id': unique_id
        }
        #if url!=None and page==None:
        task = scrapyd.schedule('default','paytm_crawler',
                                settings=settings, search_data=querystring)
        task1 = scrapyd.schedule('default','snapdeal_crawler',
                                 settings=settings, search_data=querystring)
        time.sleep(20)
        status = scrapyd.job_status('default', task)
        status1 = scrapyd.job_status('default', task1)
        obj=ScrapyItem.objects.get(unique_id=unique_id)
        for i in obj.paytm_data.values():
            results.append(i)
        for i in obj.snapdeal_data.values():
            results.append(i)
        print(results[0])
        # paginator = Paginator(results, 5)
        # products = paginator.get_page(page)
        return render (request, 'web_interface/results.html', {
            'querystring': querystring,
            'results': results,
        })

    else:
        return render(request, 'web_interface/search.html', {})

def viewdata(request):
    if request.method =='GET':
        all_objs=[]
        paginator = Paginator(all_objs, 5)
        page = request.GET.get('page')
        profiles = paginator.get_page(page)
        return render(request,'web_interface/results.html',{'results' : profiles})

scraping_project/web_interface/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load i18n %}

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">
           -->
        <title> {% block title %} Web Scraper {% endblock %} </title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this site -->
        {% block head %}
        {% endblock head %}

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        {% block body %}
        <header>
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'web_interface:searchdata' %}">Web Scraper</a>
                    </div>
                </div>
            </nav>
        </header>

        <main>
            <div class="container">
                {% block main %}
                {% endblock main %}
            </div>
        </main>
        <!-- Site footer -->
        <!-- Bootstrap core JavaScript
             ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% endblock body %}
    </body>
</html>

scraping_project/web_interface/templates/paginator.html
<ul class="pagination">
    {% if paginator.has_previous %}
    <li><a href="?q={{q}}&page={{ paginator.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.paginator.page_range %}
    {% if paginator.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?q={{q}}&page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if paginator.has_next %}
    <li><a href="?q={{q}}&page={{ paginator.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>

scraping_project/web_interface/templates/web_interface/partial_results_menu.html
{% load i18n %}

<h2 align="center">{% trans 'Profiles' %}</h2>
{% if results %}
<ul class="articles-results">
    {% for profile in results %}
    <h4><a href="/enterdata/profile/{{ profile.id }}">AF</a></h4>
    <div class="article-content">
        {{ profile.first_name}}
        {{ profile.last_name}}</div>
    </li>
    {% endfor %}
</ul>
{% else %}
<h4 class="no-result">{% trans 'No Profile found' %} :(</h4>
{% endif %}

scraping_project/web_interface/templates/web_interface/results.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %} Search {% endblock %}

{% block head %}
<link href="{% static 'css/search.css' %}" rel="stylesheet">
<link href="{% static 'css/articles.css' %}" rel="stylesheet">
<script src="{% static 'js/search.js' %}"></script>
{% endblock head %}

{% block main %}
<div class="page-header">
    <div class="row">
        <div class="col-md-3">
            <h1 align="center">{% trans 'Search Results' %}</h1>
            {% if results %}
            <section class="articles">
                {% for result in results %}
                <article>
                    <h2><a href="{{result.3}}" target="_blank">{{result.1}}</a></h2>
                    <div class="content">
                        {{ result.1 }} + {{result.2}}
                    </div>
                </article>
                {% endfor %}
            </section>
        </div>
        {% else %}
        <h4 class="no-result">{% trans 'No Product found' %} :(</h4>
        {% endif %}

    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {% include 'paginator.html' with paginator=results q=querystring %}
    </div>
</div>

{% endblock main %}

scraping_project/web_interface/templates/web_interface/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}


{% block title %} Search {% endblock %}

{% block head %}
<link href="{% static 'css/search.css' %}" rel="stylesheet">
{% endblock head %}

{% block main %}

<div class="row" style="padding-top: 4em; padding-bottom: 8em;">
    <div class="col-md-8 col-md-offset-2">
        <h3>{% trans "Search Products" %}</h3>
        <form class="navbar-form navbar-left" role="search" action="">
        <div class="input-group">
            <input type="text" class="form-control searchin" id="auto-search" name="q" placeholder="Search" size="60">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
        </form>
    </div>
</div>
{% endblock main %}